[hooks]
pre-commit = """\
    cargo fmt -- --check \
    && cargo test --workspace --bins --examples --tests \
    && cargo clippy --workspace --bins --examples --tests -- -D warnings \
    && cargo sync-readme && git add README.md \
    && typos \
"""
pre-push = """\
    cargo sync-readme -c \
"""

[logging]
verbose = true
