[package]
description = "A wrapper around `sqlx::Error` to provide error path and additional context"
edition = "2024"
license = "MIT"
name = "sqlx-error"
repository = "https://github.com/imbolc/sqlx-error"
version = "0.5.1"

[dependencies]
code-path = "0.3"
sqlx-core = { version = "0.8" }

[dev-dependencies]
sqlx = { version = "0.8", features = ["runtime-tokio-rustls"] }
thiserror = "2"
